### ISSUE TITLE
Failing to record data 19.0.0 and HDT 1.13.13

### ISSUE THREAD

**Issue by AnacondaHL** [jawslouis/Battlegrounds-Match-Data#13]
I believe the update to HDT 1.13.13 broke the ability to save game data. Data is missing both in the local CSV file, website, and the Google Sheets upload.

**Comment by unw1s3** [comment]
I agree,same

**Comment by jawslouis** [comment]
The latest update to HDT 1.13.14 might have fixed the issue. I tried it on this version and it seems to be recording fine. If the issue still persists after the update, could you create and post the log file here by taking the following steps:
- Restart HDT and make sure the plugin is enabled
- Start a new game of battlegrounds
- After the game has ended, and you are back in the menu system, go to `%AppData%\HearthstoneDeckTracker\Logs`
- Attach the file `hdt_log.txt` to a comment here

This will help me to figure out what the problem is, since I can't reproduce it on my system

**Comment by unw1s3** [comment]
Now it's working properly. Thank you.

**Comment by AnacondaHL** [comment]
Same here, updating to HDT 1.13.14 has resolved the issue, presumably related to the fix "Fixed an issue where Bob's Buddy mistook the player's board."

Thanks for looking into it!
